import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import type { App } from 'supertest/types';
import request from 'supertest';
import {
  afterAll,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from 'vitest';
import { AppModule } from '../app.module';
import { DATABASE_CONNECTION } from '../database/database-connection';
import {
  db,
  getTestConnectionString,
  hasPostgres,
  setUpPostgres,
  tearDownPostgres,
} from '../../test/sync/postgres-fixture';
import * as schema from '../database/schema';
import { eq } from 'drizzle-orm';
import { sendResetPasswordEmail } from '../email/reset-password-email';

vi.mock('../email/reset-password-email', () => ({
  sendResetPasswordEmail: vi.fn(),
}));

const describePostgres = hasPostgres ? describe : describe.skip;

describePostgres('Better Auth Password Reset Endpoints Integration', () => {
  let app: INestApplication<App>;

  const previousEnvironment = {
    databaseUrl: process.env.DATABASE_URL,
    frontendUrl: process.env.FRONTEND_URL,
    authSecret: process.env.BETTER_AUTH_SECRET,
    authUrl: process.env.BETTER_AUTH_URL,
  };

  beforeAll(async () => {
    await setUpPostgres();
    process.env.DATABASE_URL = getTestConnectionString();
    process.env.FRONTEND_URL = 'http://localhost:5173';
    process.env.BETTER_AUTH_SECRET = 'test-secret-at-least-32-characters';
    process.env.BETTER_AUTH_URL = 'http://localhost:3000';

    const moduleFixture = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(DATABASE_CONNECTION)
      .useValue(db)
      .compile();

    app = moduleFixture.createNestApplication({ logger: false });
    await app.init();
  }, 30_000);

  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterAll(async () => {
    await app?.close();
    await tearDownPostgres();

    process.env.DATABASE_URL = previousEnvironment.databaseUrl;
    process.env.FRONTEND_URL = previousEnvironment.frontendUrl;
    process.env.BETTER_AUTH_SECRET = previousEnvironment.authSecret;
    process.env.BETTER_AUTH_URL = previousEnvironment.authUrl;
  }, 30_000);

  it('handles the complete forgot-password and reset-password flow against PostgreSQL', async () => {
    const testEmail = `reset_${Date.now()}@example.test`;
    const initialPassword = 'InitialPassword123!';
    const newPassword = 'NewResetPassword123!';

    // 1. Sign up a user via HTTP endpoint
    const signUpRes = await request(app.getHttpServer())
      .post('/api/auth/sign-up/email')
      .set('Origin', 'http://localhost:5173')
      .send({
        email: testEmail,
        password: initialPassword,
        name: 'Reset Test User',
        timezone: 'UTC',
      })
      .expect(200);

    const signUpBody = signUpRes.body as { user: { id: string } };
    const userId = signUpBody.user.id;
    expect(userId).toBeDefined();

    // 2. POST /api/auth/request-password-reset generates a token and triggers sendResetPasswordEmail
    const forgetRes = await request(app.getHttpServer())
      .post('/api/auth/request-password-reset')
      .set('Origin', 'http://localhost:5173')
      .send({
        email: testEmail,
        redirectTo: 'http://localhost:5173/reset-password',
      })
      .expect(200);

    expect(forgetRes.body).toMatchObject({ status: true });

    // Verify sendResetPasswordEmail was called
    const mockedSendEmail = vi.mocked(sendResetPasswordEmail);
    expect(mockedSendEmail).toHaveBeenCalledTimes(1);
    const emailArgs = mockedSendEmail.mock.calls[0]?.[0];
    expect(emailArgs?.to).toBe(testEmail);
    expect(emailArgs?.text).toContain(
      'http://localhost:5173/reset-password?token=',
    );

    // Extract the token generated by better-auth
    const tokenMatch = emailArgs?.text.match(/token=([^&\s]+)/);
    expect(tokenMatch).not.toBeNull();
    const tokenValue = tokenMatch?.[1] ?? '';

    // Query DB verification table directly to verify database token row
    const verificationRecord = (await db.query.verification.findFirst({
      where: eq(schema.verification.identifier, `reset-password:${tokenValue}`),
    })) as { value: string; identifier: string } | undefined;
    expect(verificationRecord).toBeDefined();
    expect(verificationRecord?.value).toBe(userId);

    // Get old password hash from account table
    const oldAccountRecord = (await db.query.account.findFirst({
      where: eq(schema.account.userId, userId),
    })) as { password?: string } | undefined;

    // 3. POST /api/auth/reset-password with valid token updates the user password hash in DB
    const resetRes = await request(app.getHttpServer())
      .post('/api/auth/reset-password')
      .set('Origin', 'http://localhost:5173')
      .send({
        newPassword,
        token: tokenValue,
      })
      .expect(200);

    expect(resetRes.body).toMatchObject({ status: true });

    // Verify DB password hash has changed
    const updatedAccountRecord = (await db.query.account.findFirst({
      where: eq(schema.account.userId, userId),
    })) as { password?: string } | undefined;
    expect(updatedAccountRecord?.password).not.toBe(oldAccountRecord?.password);

    // 4. Reusing the same token returns a 400 Bad Request error
    await request(app.getHttpServer())
      .post('/api/auth/reset-password')
      .set('Origin', 'http://localhost:5173')
      .send({
        newPassword: 'AnotherPassword123!',
        token: tokenValue,
      })
      .expect(400);

    // 5. Sending an invalid/non-existent token returns a 400 Bad Request error
    await request(app.getHttpServer())
      .post('/api/auth/reset-password')
      .set('Origin', 'http://localhost:5173')
      .send({
        newPassword: 'AnotherPassword123!',
        token: 'invalid_fake_token_123',
      })
      .expect(400);
  });
});
